@echo off
rem ---------------------------------------------------------------------------
rem Starts hush-server with its configuration. This is the file the
rem administrator edits; the scheduled task calls this, not the .exe directly,
rem because the environment variables are defined here.
rem
rem Edit the values below and leave the rest alone.
rem ---------------------------------------------------------------------------

rem --- Network ---------------------------------------------------------------
rem Listen on localhost ONLY: outside traffic comes in through Apache. Do not
rem change this to 0.0.0.0 unless you know what you are doing: the server speaks
rem plain HTTP and exposing it directly would defeat TLS.
set HUSH_ADDR=127.0.0.1:8080

rem Apache sits in front, so the per-IP rate limit must use the X-Forwarded-For
rem header instead of always seeing Apache's address.
set HUSH_TRUST_PROXY=1

rem --- Database --------------------------------------------------------------
rem Path to the SQLite file. The folder must exist and the account running the
rem service needs write access. Accounts, the message queue and the encrypted
rem archive live here: this is the only thing that needs backing up.
set HUSH_DB=sqlite://C:/hush/data/hush.sqlite3?mode=rwc

rem --- Logging ---------------------------------------------------------------
rem info in production. debug records who writes to whom and when, which is
rem exactly the metadata best kept off disk.
set HUSH_LOG=info

rem Log file. As a scheduled task there is no console to look at, so without
rem this the log is lost. Any absolute path works: another drive
rem (D:\logs\hush.log) or a network share (\\server\logs\hush.log). The folder
rem is created automatically. It rotates daily: hush.log.2026-08-02, and old
rem files are removed according to HUSH_LOG_KEEP_DAYS.
set HUSH_LOG_FILE=C:\hush\logs\hush.log

rem Days of rotated logs to keep. Older ones are deleted at startup and once a
rem day. Only files generated by the server itself are touched, never anything
rem else in that folder. With 0 nothing is deleted and logs are kept forever.
set HUSH_LOG_KEEP_DAYS=30

rem --- Mail ------------------------------------------------------------------
rem Without this nobody can verify their account or recover a password.
set HUSH_SMTP_HOST=192.168.210.101
set HUSH_SMTP_PORT=25
set HUSH_SMTP_FROM=hush@lineage2.es
rem Uncomment if the relay requires authentication or STARTTLS:
rem set HUSH_SMTP_USER=user
rem set HUSH_SMTP_PASS=password
rem set HUSH_SMTP_STARTTLS=1

rem --- NEVER in production ----------------------------------------------------
rem HUSH_ECHO_CODE would return verification codes in the HTTP response. The
rem server already ignores it when SMTP is configured, but do not set it.

rem Full path on purpose: with NoDefaultCurrentDirectoryInExePath=1 (common on
rem hardened servers) cmd does not look for executables in the current
rem directory, so a bare "hush-server.exe" fails even after the cd above.
cd /d "%~dp0"
"%~dp0hush-server.exe"
